name: Android CI
on:
  push:
    branches: [ "main" ]
    paths-ignore: [ "**.md", "LICENSE", ".gitignore", ".github/ISSUE_TEMPLATE/**", "art/**", "fastlane/**", "script/**" ]
  pull_request:
    branches: [ "main" ]
    paths-ignore: [ "**.md", "LICENSE", ".gitignore", ".github/ISSUE_TEMPLATE/**", "art/**", "fastlane/**", "script/**" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: set up JDK 21
        uses: actions/setup-java@v4.7.1
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Install NDK 27.0.12077973
        run: echo "y" | sudo ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --install 'ndk;27.0.12077973'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Write sign info
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main' && github.repository == 'Super12138/ToDo'
        run: |
          if [ ! -z "${{ secrets.SIGNING_KEY }}" ]; then
            echo releaseStorePassword='${{ secrets.KEY_STORE_PASSWORD }}' >> gradle.properties
            echo releaseKeyAlias='${{ secrets.ALIAS }}' >> gradle.properties
            echo releaseKeyPassword='${{ secrets.KEY_PASSWORD }}' >> gradle.properties
            echo releaseStoreFile='${{ github.workspace }}/key.jks' >> gradle.properties
            echo ${{ secrets.SIGNING_KEY }} | base64 --decode > ${{ github.workspace }}/key.jks
          fi

      # - name: Cache NDK
        # uses: actions/cache@v4.2.3
        # with:
          # path: ${ANDROID_HOME}/ndk/27.0.12077973
          # key: ndk-cache

      - name: Fix Permissions for Debug Keystore Path
        if: github.ref != 'refs/heads/main'
        run: sudo chmod -R 777 /home/runner/.config/.android
      
      - name: Build with Gradle
        run: ./gradlew assembleRelease

      - name: Upload APK
        if: success() && github.event_name != 'pull_request' && github.repository == 'Super12138/ToDo'
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Release
          path: ${{ github.workspace }}/app/build/outputs/apk/release